services:
  ssh-server:
    image: linuxserver/openssh-server:latest
    container_name: ssh-server
    hostname: ssh-server
    environment:
      - PUID=1000 # Your user ID on the Raspberry Pi
      - PGID=1000 # Your group ID on the Raspberry Pi
      - TZ=Etc/UTC # Your timezone
      - DOCKER_MODS=linuxserver/mods:openssh-server-auto-users
      - PASSWORD_ACCESS=false
      - PUBLIC_KEY_FILE=/config/ssh/authorized_keys
    volumes:
      - ./ssh_config:/config
    # Optional: for direct SSH testing to the container if needed
    # ports:
    #   - "2222:2222"
    restart: unless-stopped

  ngrok-tunnel:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_GITHUB_CLIENT_ID=${NGROK_GITHUB_CLIENT_ID}
      - NGROK_GITHUB_CLIENT_SECRET=${NGROK_GITHUB_CLIENT_SECRET}
      - NGROK_GITHUB_ALLOWED_EMAILS=${NGROK_GITHUB_ALLOWED_EMAILS}
      - NGROK_DEBUG=true
    command:
      # Use an HTTP tunnel for OAuth
      - "http"
      - "http://ssh-server:2222" # Tunnel to the SSH server container's exposed port
      - "--oauth=github"          # Enable GitHub OAuth for the HTTP tunnel
      # - "--oauth-allow-email=${NGROK_GITHUB_ALLOWED_EMAILS}" # Uncomment if using NGROK_GITHUB_ALLOWED_EMAILS
    depends_on:
      - ssh-server
    restart: unless-stopped