# docker-compose.yml
version: '3.8'

services:
  # Service for the ngrok tunnel
  ngrok-tunnel:
    image: ngrok/ngrok:latest # The official ngrok Docker image
    container_name: ngrok-tunnel
    environment:
      # Pass the ngrok authtoken from the .env file
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DEBUG=true # Enable debug logging for more verbose output (useful for troubleshooting)
    command:
      # The 'tcp' command establishes a direct TCP tunnel
      - "tcp"
      # '--remote-addr' specifies the reserved TCP address ngrok should assign this tunnel to.
      # Replace '1.tcp.ngrok.io:12345' with YOUR SPECIFIC Reserved TCP Address and Port from ngrok dashboard.
      - "--remote-addr=3.tcp.ngrok.io:26644"
      # The local address where the ngrok agent will forward traffic inside your Docker network.
      # 'ssh-server' refers to the SSH server service defined above, and '2222' is its SSH port.
      - "host.docker.internal:22"
    restart: unless-stopped # Always restart unless explicitly stopped